export { default as Book } from "./Book";
export { default as BookList } from "./BookList";
export { default as BriefCase } from "./BriefCase";
export { default as Calendar} from "./Calendar";
export { default as Download} from "./Download";
export { default as Education } from "./Education";
export { default as Email} from "./Email";
export { default as Github} from "./Github";
export { default as Graduation } from "./Graduation"
export { default as Home } from "./Book";
export { default as Linkedin} from "./Linkedin";
export { default as Location} from "./Location";
export { default as Mom } from "./Mom";
export { default as Phone} from "./Phone";
export { default as Sun } from "./Sun";
export { default as Telegram } from "./Telegram";
export { default as User } from "./User";
export { default as WorkI } from "./WorkI";
export { default as Brain} from "./Brain";
export { default as Line} from "./Line";
export { default as Bd} from "./Bd";
export { default as Back} from "./Back";
export { default as Front} from "./Front";
export { default as Debug} from "./Debug";